### ISSUE TITLE
Trouble loading Harvester.Integration.NLog extension

### ISSUE THREAD

**Issue by bondman** [cbaxter/Harvester#25]
Hi, 

I am getting the following exception report when trying to step over the following line of code

  public class NLogLogger : ILogger
    {
        private NLog.Logger _log;

        public NLogLogger()
        {
            _log = LogManager.GetCurrentClassLogger(); //   <============================
        }
=========================================================================

Unhandled Exception: NLog.NLogConfigurationException: Error loading extensions: Harvester.Integration.NLog, Version=2.1.0.0, Culture=neutral, PublicKeyToken=2335e074c59acad6 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Harvester.Integration.NLog, Version=2.1.0.0, Culture=neutral, PublicKeyToken=2335e074c59acad6' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at NLog.Config.XmlLoggingConfiguration.ParseExtensionsElement(NLogXmlElement extensionsElement, String baseDirectory)
   --- End of inner exception stack trace ---
   at NLog.Config.XmlLoggingConfiguration.ParseExtensionsElement(NLogXmlElement extensionsElement, String baseDirectory)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String baseDirectory)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String baseDirectory)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   at NLog.Config.XmlLoggingConfiguration..ctor(String fileName)
   at NLog.LogFactory.LoadLoggingConfiguration(String configFile)
   at NLog.LogFactory.get_Configuration()
   at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
   at NLog.LogFactory.GetLogger(String name)
   at NLog.LogManager.GetCurrentClassLogger()

**Comment by cbaxter** [comment]
@bondman Closing as per our conversations, created a separate issue to address nuspec version.
